# Override http_archive for local testing
local_repository(
    name = "contrib_rules_git",
    path = "../..",
)

#---SNIP--- Below here is re-used in the workspace snippet published on releases

######################
# rules_git setup #
######################
# Fetches the rules_git dependencies.
# If you want to have a different version of some dependency,
# you should fetch it *before* calling this.
# Alternatively, you can skip calling this function, so long as you've
# already fetched all the dependencies.
load("@contrib_rules_git//git:repositories.bzl", "rules_git_dependencies")

rules_git_dependencies()
